theme = "onedark"

[editor]
scrolloff = 15
shell = ["bash", "-c"]
cursorline = true
auto-completion = true
# path-completion = true
auto-format = true
insert-final-newline = false
# clipboard-provider = "wayland"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
# diagnostics = ["warning", "error"]
# workspace-diagnostics = ["warning", "error"]

[editor.lsp]
enable = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
# '```' = '```'

[editor.whitespace.render]
tab = "all"
space = "none"

[editor.whitespace.characters]
tab = "→"


